on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: 🚀 Deploy OVHwebsite on pull request on test
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVEROVH }}
        username: ${{ secrets.FTP_USEROVH }}
        password: ${{ secrets.FTP_PASSWORDOVH }}
        server-dir: /www/tests/
